.babelrc
.eslintrc
.lintstagedrc
.prettierrc
assetTransformer.js
package.json
src/components/App/App.jsx
src/components/App/App.test.js
src/components/App/App.test.jsx
src/components/App/__snapshots__/App.test.jsx.snap
src/index.js
src/serviceWorker.js
src/stories/index.story.js
yarn.lock

- Setup the ESlint rules
- Setup the pre-commit config
- Adding enzyme
- Add and config the `assertTransformer.js`
- ` eslint src/ --fix `
- ` git add . `
- ` jest --findRelatedTests `

Updating eslint config

---

.babelrc
package.json
src/components/FactoryBlock/Block.css
src/components/Game/Game.constants.js
src/components/Game/Game.css
src/components/Game/Game.jsx
src/components/Game/Game.spec.jsx
src/components/Game/__snapshots__/Game.spec.jsx.snap
src/components/MachineTypes/MachineTypes.constants.js
src/components/MachineTypes/MachineTypes.css
src/components/MachineTypes/MachineTypes.jsx
src/components/Resources/ResourcesBar.css
src/components/Resources/ResourcesBar.jsx
src/stories/Game/Game.story.js
yarn.lock

- Adding Game component
- Using the current resource component
- Using the machine types component
- Add the edit component
- Add the details component
- Missing game tests

Game entity

---

.eslintrc
package.json
src/components/App/App.jsx
src/reducers/simpleReducer.js
src/store/Reducers.js
src/store/ReduxStore.js
yarn.lock

- Make sure that redux dependency exists
- Config a redux store within App
- Create actions folder
- Create selectors folder
- Create reducers folder
- Setup an initial reducer

Add Redux Store

---

package.json
src/actions/Currency.js
src/actions/GameState.js
src/components/App/App.jsx
src/components/App/__snapshots__/App.test.jsx.snap
src/components/Game/Game.jsx
src/components/Game/Game.spec.jsx
src/components/Game/GameConnector.js
src/reducers/GameState.js
src/reducers/Grid.js
src/selectors/GameDimensions.js
src/store/Reducers.js
src/utils/actionTypes.js
src/utils/defaultValues.js
yarn.lock

- Use Game in App.js
- Create a `GameConnector` connecting Game with redux
- Create some Reducers files
- Create typeActions file
- Create some Actions files
- Create a selector
- Add `GameState` and `Grid` to redux store
- Add Tick for each 3 seconds
- Create defaultValues file
- Adding ` redux-mock-store` dependency
- Updating `Game.spec.js` using a mockStore

Connect current components with redux and setup the Tick

---

src/components/App/App.jsx
src/components/App/__snapshots__/App.test.jsx.snap
src/components/FactoryBlock/Block.css
src/components/FactoryBlock/Block.jsx
src/components/FactoryBlock/__snapshots__/Block.spec.jsx.snap
src/components/FactoryGrid/__snapshots__/FactoryGrid.spec.jsx.snap
src/components/Game/Game.css
src/components/Game/Game.jsx
src/components/Game/__snapshots__/Game.spec.jsx.snap
src/components/MachineTypes/MachineTypes.css
src/components/MachineTypes/MachineTypes.jsx
src/components/Resources/ResourcesBar.css
src/components/Resources/ResourcesBar.jsx
src/components/Resources/__snapshots__/ResourcesBar.spec.jsx.snap
src/stories/Game/Game.story.js
src/stories/Resources/ResourcesBar.story.js

Adding some styles

---

.storybook/config.js
jestSetup.js
package.json
src/components/Detail/Detail.css
src/components/Detail/Detail.jsx
src/components/Detail/Detail.spec.jsx
src/stories/Detail/Detail.story.jsx

Issue.#46.create detail component

---

src/actions/Currency.js
src/actions/GameState.js
src/actions/Grid.js
src/components/App/__snapshots__/App.test.jsx.snap
src/components/FactoryBlock/Block.css
src/components/FactoryBlock/Block.jsx
src/components/FactoryBlock/Block.spec.jsx
src/components/FactoryBlock/BlockConnector.js
src/components/FactoryBlock/__snapshots__/Block.spec.jsx.snap
src/components/FactoryGrid/FactoryGrid.jsx
src/components/FactoryGrid/FactoryGrid.spec.jsx
src/components/FactoryGrid/FactoryGridConnector.js
src/components/FactoryGrid/__snapshots__/FactoryGrid.spec.jsx.snap
src/components/Game/Game.jsx
src/components/Game/Game.spec.jsx
src/components/Game/__snapshots__/Game.spec.jsx.snap
src/components/Machine/Machine.jsx
src/components/Machine/MachineConnector.js
src/reducers/GameState.js
src/reducers/Grid.js
src/selectors/GameState.js
src/selectors/Grid.js
src/stories/FactoryBlock/FactoryBlock.story.js
src/stories/FactoryGrid/FactoryGrid.story.js
src/stories/Game/Game.story.js
src/stories/Machine/Machine.story.js
src/stories/MachineTypes/MachineTypes.story.js
src/utils/actionTypes.js
src/utils/machineUtils.js

- Define a redux state for each grid node
- Use the redux grid state for know and render each block
- Allow select a machine type
- Allow update the current empty node

Allow add machines to Grid

---

src/components/FactoryBlock/Block.spec.jsx
src/components/FactoryBlock/BlockConnector.js
src/components/FactoryBlock/__snapshots__/Block.spec.jsx.snap
src/components/FactoryGrid/FactoryGrid.jsx
src/components/FactoryGrid/FactoryGrid.spec.jsx
src/components/FactoryGrid/FactoryGridConnector.js
src/selectors/Grid.js
src/stories/FactoryBlock/FactoryBlock.story.jsx

This pr remove the task of FactoryGrid about of know which are the redux grid nodes
This closes #73

A block only receive his node data of redux

---

src/actions/GameState.js
src/components/App/__snapshots__/App.test.jsx.snap
src/components/Edition/Edition.jsx
src/components/EditionOption/EditionActionConnector.js
src/components/EditionOption/EditionOption.css
src/components/EditionOption/EditionOption.jsx
src/components/FactoryBlock/Block.css
src/components/Game/__snapshots__/Game.spec.jsx.snap
src/reducers/GameState.js
src/selectors/GameState.js
src/stories/Edition/Edition.story.jsx
src/stories/EditionOption/EditionOption.story.jsx
src/utils/actionTypes.js
src/utils/editionUtils.js

- When a edition mode is clicked, the redux store should be updated
- The current selected mode should has a border
This pr closes #72

Issue.#72.setup edition state 

---

src/components/Detail/Detail.css
src/components/Detail/Detail.jsx

Adding consistent style to details

---

src/components/Machine/Machine.css

This pr is very simple, its only for be consist with the other style

Change the machine types border color

---

src/components/Machine/Machine.css
src/components/Machine/Machine.jsx
src/components/Machine/MachineConnector.js

When a machine type is selected, a border is applied to him

---

src/stories/FactoryGrid/FactoryGrid.story.jsx
src/stories/Game/Game.story.jsx
src/stories/Machine/Machine.story.jsx
src/stories/MachineNodes/CrafterMachineNode.story.jsx
src/stories/MachineNodes/EmptyMachineNode.story.jsx
src/stories/MachineNodes/FurnaceMachineNode.story.jsx
src/stories/MachineNodes/SellerMachineNode.story.jsx
src/stories/MachineNodes/StarterMachineNode.story.jsx
src/stories/MachineNodes/TransporterMachineNode.story.jsx
src/stories/MachineTypes/MachineTypes.story.jsx

It fixes some storybooks which weren't working.
Fixes #104
I tested it looking the storybooks

add fixes for all the storybooks that are super coupled with the redux store

---

src/components/FactoryBlock/Block.jsx

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes #102  (issue)
Please delete options that are not relevant.
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

Fix bug that allowed create a machine in a node that have another machine

---

src/components/App/App.jsx
src/components/App/App.test.jsx
src/components/Game/Game.jsx
src/components/Game/Game.spec.jsx
src/components/Game/GameConnected.js
src/components/Game/GameConnector.js
src/components/LeftPanel/LeftPanel.jsx
src/components/Ticker/Clicker/Clicker.css
src/components/Ticker/Clicker/Clicker.jsx
src/components/Ticker/Clicker/Clicker.spec.jsx
src/components/Ticker/Clicker/ClickerConnected.js
src/components/Ticker/Clicker/ClickerConnector.js
src/components/Ticker/Frequency/Frequency.css
src/components/Ticker/Frequency/Frequency.jsx
src/components/Ticker/Frequency/Frequency.spec.jsx
src/components/Ticker/Frequency/FrequencyConnected.js
src/components/Ticker/Frequency/FrequencyConnector.js

This PR add a refactor for the game component
Fixes #121 
* OS: Ubuntu 16.04
* Browser: Mozilla
* Hardware: Mi notebook

Issue.#121

---

cypress/integration/select-machine.spec.js
src/components/FactoryGrid/FactoryGridConnected.js
src/components/FactoryGrid/FactoryGridConnector.js
src/components/Game/GameConnected.js
src/components/Game/GameConnector.js
src/components/Machine/StarterMachine/StarterMachine.jsx
src/components/Resources/ResourcesConnector.js
src/components/Ticker/Clicker/ClickerConnector.js
src/components/Ticker/Frequency/FrequencyConnected.js
src/components/Ticker/Frequency/FrequencyConnector.js

this ticket solves the bug commented on ticket 125
Fixes #125 
closes #116 
* OS: ubuntu
* Browser: mozilla
* Hardware: mipc

Issue.#125

---

src/components/Game/Game.constants.js
src/components/MachineNodes/CrafterMachineNode/CrafterMachineNode.jsx
src/components/MachineNodes/CrafterMachineNode/CrafterMachineNode.spec.jsx
src/components/MachineNodes/CrafterMachineNode/CrafterMachineNodeConnected.js
src/components/MachineNodes/CrafterMachineNode/CrafterMachineNodeConnector.js
src/utils/machineUtils.js

This pr adds the crafter production functionality :)
Before merge this one, we need merge https://github.com/PracticaDS/pdes-tp-team_prog/pull/127
- Would be great create a test for this behavior
Fixes 
Please delete options that are not relevant.
* OS: 
* Browser: 
* Hardware:

Issue.#89.crafter production

---

src/components/FactoryBlock/BlockUtils.js

Add missing validation
Fixes #132 
Please delete options that are not relevant.
* OS: 
* Browser: 
* Hardware:

Add missing validation for create a new machine in the grid

---

src/components/FactoryGrid/FactoryGrid.css
src/components/FactoryGrid/FactoryGridConnected.js
src/components/Game/Game.constants.js
src/components/MachineNodes/StarterMachineNode/StarterMachineNode.jsx

This pr adds a form of render the material of each position
Fixes 
Please delete options that are not relevant.
* OS: 
* Browser: 
* Hardware:

Issue.#115.show materials

---

src/actions/GameState.js
src/actions/utils.js
src/components/Ticker/Frequency/Frequency.jsx
src/components/Ticker/Frequency/FrequencyConnector.js
src/layouts/Home/Home.jsx
src/reducers/GameState.js
src/reducers/User.js

add create, get, delete games to backend api sync
Fixes # (looking)
* OS: 
* Browser: 
* Hardware:

add create, get, delete games

---

src/components/Login/Login.css
src/components/Login/Login.jsx
src/components/Login/constants.js

This pr adds style to Login tab

Login style

---

src/layouts/Home/Home.css
src/layouts/Home/Home.jsx
src/layouts/Home/constants.js

This pr adds style to Home Tab

Home view style

---

src/actions/GameState.js
src/actions/utils.js
src/layouts/Home/CreateGame.jsx
src/layouts/Home/Home.jsx
src/layouts/Home/HomeConnector.js
src/layouts/Home/constants.js

add game modal form
Fixes # (158)

add game form modal

---

src/actions/GameState.js

Hotfix delete game
